FROM ghcr.io/allenai/pytorch:2.5.1-cuda12.4-python3.11
# FROM pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

WORKDIR /stage

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    curl \
    unzip \
    git \
    vim

COPY . /stage
RUN rm -f /stage/.env && pip install . && pip cache purge
