#!/bin/bash

if [ -z "$MODEL_NAME" ]; then
  echo "MODEL_NAME environment variable is not set. Using default: allenai/general-tool-use-dev."
  MODEL_NAME="allenai/general-tool-use-dev"
fi

# Check if MODEL_REVISION environment variable is set
if [ -z "$MODEL_REVISION" ]; then
  echo "Error: MODEL_REVISION environment variable is not set."
  exit 1
fi

if [ -z "$BEAKER_WORKSPACE" ]; then
  echo "BEAKER_WORKSPACE environment variable is not set. Using default: ai2/general-tool-use."
  BEAKER_WORKSPACE="ai2/general-tool-use"
fi

if [ -z "$EXTRA_ARGS" ]; then
  echo "EXTRA_ARGS environment variable is not set. Using default: ''"
  EXTRA_ARGS=""
fi


# Define the path to the YAML file
YAML_FILE_TEMPLATE="./vllm_server_template.yaml"
YAML_FILE="./vllm_server_copy_${MODEL_REVISION}.yaml"

# Use sed to replace <MODEL_NAME> and <MODEL_REVISION> with the values of MODEL_NAME and MODEL_REVISION
cp $YAML_FILE_TEMPLATE $YAML_FILE
sed -i.bak "s|<MODEL_NAME>|$MODEL_NAME|g" "$YAML_FILE"
sed -i.bak "s|<MODEL_REVISION>|$MODEL_REVISION|g" "$YAML_FILE"
sed -i.bak "s|<EXTRA_ARGS>|$EXTRA_ARGS|g" "$YAML_FILE"
# Remove the backup file generated by -i.bak
rm "$YAML_FILE.bak"

beaker experiment create "$YAML_FILE" -w "$BEAKER_WORKSPACE"
